# syntax = docker/dockerfile:1

ARG RUBY_VERSION=3.2.3
FROM registry.docker.com/library/ruby:$RUBY_VERSION-slim

ARG USERNAME=user
ARG GROUPNAME=user
ARG UID=1000
ARG GID=1000

WORKDIR /work

ENV BUNDLE_PATH="vendor/bundle"

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libpq-dev libmagic-dev libvips pkg-config vim graphviz

COPY . .

RUN groupadd -g ${GID} ${GROUPNAME} && \
    useradd -m -s /bin/bash -u ${UID} -g ${GID} ${USERNAME}

# ENTRYPOINT ["/work/bin/docker-entrypoint"]

EXPOSE 3000
CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
