services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        GID: ${GID:-1000}
        UID: ${UID:-1000}
    image: ${PROJECT_NAME}-rails
    container_name: ${PROJECT_NAME}-rails
    # ports:
    #   - "${DEV_HOST_IP-127.0.0.1}:3000:3000"
    tty: true
    stdin_open: true
    env_file:
      - .env.rails
      - .env.rails.secret
    volumes:
      - .:/work
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis:16-3.4
    container_name: ${PROJECT_NAME}-postgres
    ports:
      - "${DEV_HOST_IP:-127.0.0.1}:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: ${PROJECT_NAME}-postgres-data

networks:
  default:
    name: ${PROJECT_NAME}
    external: true
